apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-spring
  template:
    metadata:
      labels:
        app: demo-spring
    spec:
      containers:
      - name: demo-spring
        image: demo-spring:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo-spring-service
spec:
  type: NodePort
  selector:
    app: demo-spring
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080